version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch-demo
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data


  nodejs:
    build: 
      context: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esdata:

  



